 meta_product_name: "Our Space & Health"
 meta_title: "Our Space & Health - The control of your health" 
 meta_description: ""
 # meta_image: "cover.png" # should exist in `app/assets/images/`
 # twitter_account: "@product_twitter_account" # required for Twitter Cards
 